/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloFilter.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloFilter (0 custom class methods, 0 custom properties)

#import "GTLKnedloFilter.h"

// ----------------------------------------------------------------------------
//
//   GTLKnedloFilter
//

@implementation GTLKnedloFilter
@end
