/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloHandler.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloHandler (0 custom class methods, 5 custom properties)

#import "GTLKnedloHandler.h"

#import "GTLKnedloErrorManager.h"
#import "GTLKnedloFilter.h"
#import "GTLKnedloFormatter.h"
#import "GTLKnedloLevel.h"

// ----------------------------------------------------------------------------
//
//   GTLKnedloHandler
//

@implementation GTLKnedloHandler
@dynamic encoding, errorManager, filter, formatter, level;
@end
