/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloLevel.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloLevel (0 custom class methods, 3 custom properties)

#import "GTLKnedloLevel.h"

// ----------------------------------------------------------------------------
//
//   GTLKnedloLevel
//

@implementation GTLKnedloLevel
@dynamic localizedName, name, resourceBundleName;
@end
