/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloBadge.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloBadge (0 custom class methods, 3 custom properties)

#import "GTLKnedloBadge.h"

// ----------------------------------------------------------------------------
//
//   GTLKnedloBadge
//

@implementation GTLKnedloBadge
@dynamic descriptionProperty, imageLink, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"description"
                                forKey:@"descriptionProperty"];
  return map;
}

@end
