/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloHandler.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloHandler (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLKnedloErrorManager;
@class GTLKnedloFilter;
@class GTLKnedloFormatter;
@class GTLKnedloLevel;

// ----------------------------------------------------------------------------
//
//   GTLKnedloHandler
//

@interface GTLKnedloHandler : GTLObject
@property (copy) NSString *encoding;
@property (retain) GTLKnedloErrorManager *errorManager;
@property (retain) GTLKnedloFilter *filter;
@property (retain) GTLKnedloFormatter *formatter;
@property (retain) GTLKnedloLevel *level;
@end
