/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloLevel.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloLevel (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLKnedloLevel
//

@interface GTLKnedloLevel : GTLObject
@property (copy) NSString *localizedName;
@property (copy) NSString *name;
@property (copy) NSString *resourceBundleName;
@end
