/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloBadgeCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloBadgeCollection (0 custom class methods, 1 custom properties)

#import "GTLKnedloBadgeCollection.h"

#import "GTLKnedloBadge.h"

// ----------------------------------------------------------------------------
//
//   GTLKnedloBadgeCollection
//

@implementation GTLKnedloBadgeCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLKnedloBadge class]
                                forKey:@"items"];
  return map;
}

@end
