/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloFormatter.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloFormatter (0 custom class methods, 0 custom properties)

#import "GTLKnedloFormatter.h"

// ----------------------------------------------------------------------------
//
//   GTLKnedloFormatter
//

@implementation GTLKnedloFormatter
@end
