/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedlo.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API

#import "GTLKnedloConstants.h"

#import "GTLKnedloArticle.h"
#import "GTLKnedloArticleCollection.h"
#import "GTLKnedloBadge.h"
#import "GTLKnedloBadgeCollection.h"
#import "GTLKnedloErrorManager.h"
#import "GTLKnedloFilter.h"
#import "GTLKnedloFormatter.h"
#import "GTLKnedloHandler.h"
#import "GTLKnedloLevel.h"
#import "GTLKnedloLogger.h"

#import "GTLQueryKnedlo.h"
#import "GTLServiceKnedlo.h"
