/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API

#import "GTLKnedloConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeKnedloUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
