/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloArticleCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloArticleCollection (0 custom class methods, 1 custom properties)

#import "GTLKnedloArticleCollection.h"

#import "GTLKnedloArticle.h"

// ----------------------------------------------------------------------------
//
//   GTLKnedloArticleCollection
//

@implementation GTLKnedloArticleCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLKnedloArticle class]
                                forKey:@"items"];
  return map;
}

@end
