/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLKnedloLogger.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLKnedloLogger (0 custom class methods, 5 custom properties)

#import "GTLKnedloLogger.h"

#import "GTLKnedloFilter.h"
#import "GTLKnedloHandler.h"
#import "GTLKnedloLevel.h"

// ----------------------------------------------------------------------------
//
//   GTLKnedloLogger
//

@implementation GTLKnedloLogger
@dynamic filter, handlers, level, parent, useParentHandlers;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLKnedloHandler class]
                                forKey:@"handlers"];
  return map;
}

@end
