/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryKnedlo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryKnedlo (4 custom class methods, 4 custom properties)

#import "GTLQueryKnedlo.h"

#import "GTLKnedloArticleCollection.h"
#import "GTLKnedloBadgeCollection.h"
#import "GTLKnedloLogger.h"

@implementation GTLQueryKnedlo

@dynamic action, articleLink, fields, page;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryKnedlo object.

+ (id)queryForActionWithAction:(NSString *)action
                   articleLink:(NSString *)articleLink {
  NSString *methodName = @"knedlo.action";
  GTLQueryKnedlo *query = [self queryWithMethodName:methodName];
  query.action = action;
  query.articleLink = articleLink;
  query.expectedObjectClass = [GTLKnedloBadgeCollection class];
  return query;
}

+ (id)queryForBadges {
  NSString *methodName = @"knedlo.badges";
  GTLQueryKnedlo *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLKnedloBadgeCollection class];
  return query;
}

#pragma mark -
#pragma mark "endpoint" methods
// These create a GTLQueryKnedlo object.

+ (id)queryForEndpointLog {
  NSString *methodName = @"knedlo.endpoint.log";
  GTLQueryKnedlo *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLKnedloLogger class];
  return query;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryKnedlo object.

+ (id)queryForFeed {
  NSString *methodName = @"knedlo.feed";
  GTLQueryKnedlo *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLKnedloArticleCollection class];
  return query;
}

@end
