/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLServiceKnedlo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   knedlo/v1
// Description:
//   This is an API
// Classes:
//   GTLServiceKnedlo (0 custom class methods, 0 custom properties)

#import "GTLKnedlo.h"

@implementation GTLServiceKnedlo

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = [NSArray arrayWithObjects:
                      [GTLQueryKnedlo class],
                      [GTLKnedloArticle class],
                      [GTLKnedloArticleCollection class],
                      [GTLKnedloBadge class],
                      [GTLKnedloBadgeCollection class],
                      [GTLKnedloErrorManager class],
                      [GTLKnedloFilter class],
                      [GTLKnedloFormatter class],
                      [GTLKnedloHandler class],
                      [GTLKnedloLevel class],
                      [GTLKnedloLogger class],
                      nil];
  return classes;
}
#endif  // DEBUG

- (id)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"http://192.168.218.98:80/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
