/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-10-20 at 07:52:16 UTC 
 * Modify at your own risk.
 */

package com.appspot.knedloreader.knedlo.model;

/**
 * Model definition for Logger.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the knedlo. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Logger extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Filter filter;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Handler> handlers;

  static {
    // hack to force ProGuard to consider Handler used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Handler.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Level level;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Logger parent;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean useParentHandlers;

  /**
   * @return value or {@code null} for none
   */
  public Filter getFilter() {
    return filter;
  }

  /**
   * @param filter filter or {@code null} for none
   */
  public Logger setFilter(Filter filter) {
    this.filter = filter;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Handler> getHandlers() {
    return handlers;
  }

  /**
   * @param handlers handlers or {@code null} for none
   */
  public Logger setHandlers(java.util.List<Handler> handlers) {
    this.handlers = handlers;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Level getLevel() {
    return level;
  }

  /**
   * @param level level or {@code null} for none
   */
  public Logger setLevel(Level level) {
    this.level = level;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Logger getParent() {
    return parent;
  }

  /**
   * @param parent parent or {@code null} for none
   */
  public Logger setParent(Logger parent) {
    this.parent = parent;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getUseParentHandlers() {
    return useParentHandlers;
  }

  /**
   * @param useParentHandlers useParentHandlers or {@code null} for none
   */
  public Logger setUseParentHandlers(java.lang.Boolean useParentHandlers) {
    this.useParentHandlers = useParentHandlers;
    return this;
  }

  @Override
  public Logger set(String fieldName, Object value) {
    return (Logger) super.set(fieldName, value);
  }

  @Override
  public Logger clone() {
    return (Logger) super.clone();
  }

}
